language: android

jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a ANDROID_BUILD_TOOLS=23.0.1

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository

script:
  - ./gradlew assembleRelease

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
